cc_library (
  name = "curl_op",
  srcs = [
    'curl_op.cc',
  ],

  deps = [
    "//thirdparty/glog:glog",
    "//thirdparty/gflags:gflags",
    "#pthread",
    '#curl',
    '#ssl',
    '#rt',
  ]
)

