cc_binary(
    name = 'cgidump',
    srcs = [
        'main.cpp'
    ],
    deps = [
        '//thirdparty/libpcap:pcap',
    ],
    export_incs = [
        '/home/longtao/work/front_server/thirdparty/libpcap/include',
    ],
    defs = [],
    optimize = [],
    extra_cppflags = [],
)
